# Generated by Django 5.0.2 on 2024-07-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='map_url',
            field=models.TextField(null=True),
        ),
    ]
