# Generated by Django 5.0.2 on 2024-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_url',
            field=models.URLField(null=True),
        ),
    ]
