# Generated by Django 5.0.2 on 2024-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_property_devloper_property_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('readytomove', 'Ready To Move'), ('underconstrution', 'Under Construction')], max_length=50, null=True),
        ),
    ]
