# Generated by Django 5.0.2 on 2024-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_property_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='property',
            name='main_img',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
