# Generated by Django 5.0.2 on 2024-07-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='inq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('contactno', models.PositiveIntegerField(verbose_name=10)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
