# Generated by Django 5.0.2 on 2024-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_inq_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inq',
            name='contactno',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
