# Generated by Django 5.0.2 on 2024-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_inq_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inq',
            name='contactno',
            field=models.PositiveIntegerField(),
        ),
    ]
