# Generated by Django 5.0.7 on 2024-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_inq_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price2',
            field=models.CharField(default='NONE', editable=False, max_length=255),
        ),
    ]
